export { default as Logo } from './logo/Logo'
export { default as GameCard } from './game-card/GameCard'
export { default as Navbar } from './navbar/Navbar'
export { default as SearchBar } from './search-bar/SearchBar'
export { default as Filters } from './filters/Filters'
export { default as Pagination } from './pagination/Pagination'
export { default as Loader } from './loader/Loader'
